FROM nvcr.io/nvidia/pytorch:23.06-py3
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install accelerate transformers diffusers gradio ftfy invisible_watermark
WORKDIR /app